# -*- mode: ruby -*-
# vi: set ft=ruby :

# YOU MUST HAVE THE FOLLOWING DATABASE AND WEB DIRECTORIES FOR THIS FILE TO WORK
# DB DIRECTORY : ~/vms/dev/dbRepos
# WEB DIRECTORY : ~/vms/dev/webRepos
# Creates two machines for php enviroment
# 'web' machine will have tools installed by 'webBootstrap.sh'
# 'db' machine will have tools installed by 'dbBootstrap.sh'
# commands addressing the machine name will be performed on that machine (e.g. vagrant up db, vagrant ssh web) 
# 'vagrant up' will bring up both machines

Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/trusty64"
    web.vm.provision :shell, path: "webBootstrap.sh"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.network "forwarded_port", guest: 443, host: 8443
    web.vm.synced_folder "~/vms/dev/webRepos", "/var/www/html/webRepos", :nfs=> { :mount_options=> ['dmode=777', 'fmode=777']}
    web.vm.network "private_network", ip: "192.168.13.200"
  end

  config.vm.define "db" do |db|
    if ARGV[0] == "up"
      puts "Enter desired root database password:"
      db_password = STDIN.gets.chomp
    end
    db.vm.box = "bento/ubuntu-16.04"
    db.vm.synced_folder "~/vms/dev/dbRepos", "/var/www/html/dbRepos", :nfs=> { :mount_options=> ['dmode=777', 'fmode=777']}
    db.vm.network "private_network", ip: "192.168.13.201"
    db.vm.provision "shell" do |script| 
      script.path = "dbBootstrap.sh"
      script.args = ["#{db_password}"]
    end
  end
end
